SELECT * FROM A
WHERE MATCH(STRING TEXT)
AGAINST ('STRING' IN NATURAL LANGUAGE MODE);

CREATE TRIGGER
BEFORE INSERT ON UserAnswer_ANSWERS
FOR EACH ROW
WHEN EXISTS (SELECT * 
			FROM DIRTYWORDS
			WHERE MATCH(new.ANSWERS)
			AGAINST (WORD))

CREATE TRIGGER
BEFORE INSERT ON UserAnswer_ANSWERS
FOR EACH ROW
WHEN EXISTS (SELECT * 
			FROM DIRTYWORDS
			WHERE '%new.ANSWERS%' LIKE WORD)
ROLLBACK;
			


DROP TRIGGER IF EXISTS `db2project`.`UserAnswer_ANSWERS_BEFORE_INSERT`;

DELIMITER $$
USE `db2project`$$
CREATE DEFINER = CURRENT_USER TRIGGER `db2project`.`UserAnswer_ANSWERS_BEFORE_INSERT` BEFORE INSERT ON `UserAnswer_ANSWERS` FOR EACH ROW
BEGIN
	IF( 0 < (SELECT count(*)
			FROM DIRTYWORDS
			WHERE MATCH(new.ANSWERS)
			AGAINST (WORD)))
	THEN 
		ROLLBACK;
END IF;
END;$$
DELIMITER ;
